name:       MindCraft
main:       io.github.mindcraft.MindCraft
version:    0.0.2
commands:
    iddqd:
        description: God Mode.
        permission: MindCraft.iddqd
        permission-message: You don't have <permission>